version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    networks:
      - app-network
    volumes:
      - ./backend/data.txt:/app/data.txt

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "7001:7000"  # El frontend estará disponible en el puerto 7001
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
