---
- name: Instalar Docker y Docker Compose
  hosts: local
  become: yes
  roles:
    - common

- name: Copiar archivos del proyecto al entorno local
  hosts: local
  become: yes
  tasks:
    - name: Copiar backend al entorno local
      synchronize:
        src: /mnt/c/Users/Ruben/PycharmProjects/Devps/DevOps3/backend/
        dest: /home/ubuntu/backend/
        mode: push

    - name: Copiar frontend al entorno local
      synchronize:
        src: /mnt/c/Users/Ruben/PycharmProjects/Devps/DevOps3/frontend/
        dest: /home/ubuntu/frontend/
        mode: push

    - name: Copiar DevOps al entorno local
      synchronize:
        src: /mnt/c/Users/Ruben/PycharmProjects/Devps/DevOps3/DevOps/  # La ruta completa de DevOps
        dest: /home/ubuntu/DevOps/
        mode: push

    - name: Copiar archivo docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

- name: Gestionar microservicios con Docker Compose
  hosts: local
  become: yes
  tasks:
    - name: Iniciar microservicios
      community.docker.docker_compose_v2:
        project_src: /mnt/c/Users/Ruben/PycharmProjects/Devps/DevOps3
        state: present
      tags: start

    - name: Detener microservicios
      community.docker.docker_compose_v2:
        project_src: /mnt/c/Users/Ruben/PycharmProjects/Devps/DevOps3
        state: absent
      tags: stop



